name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test-libraryManager:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Step 3 - Run unit tests
        working-directory: .
        run: |
          echo "Loading... Running unit tests for libraryManager"
          mvn clean verify -Dtest=*IT
          
      - name: Step 4 - Get Surefire Reports Path
        id: surefire-reports
        run: |
          echo "surefire-reports-path=$(find . -type d -name 'surefire-reports')" >> $GITHUB_OUTPUT

      - name: Step 5 - Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-libraryManager
          path: ${{ steps.surefire-reports.outputs.surefire-reports-path }}
          
      - name: Step 6 - Get JaCoCo Report Path
        id: jacoco-report
        run: |
          echo "jacoco-report-path=$(find . -type f -name 'index.html' | grep 'target/site/jacoco/index.html')" >> $GITHUB_OUTPUT

      - name: Step 7 - Upload code coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report-libraryManager
          path: ${{ steps.jacoco-report.outputs.jacoco-report-path }}
